language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      env: deps=low

env:
  global:
    - deps=no

before_install:
  - composer self-update

install:
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
  
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then export PHPUNIT_FLAGS='--coverage-clover ./build/logs/clover.xml'; fi

script:
  - ./vendor/bin/phpunit -v $PHPUNIT_FLAGS

after_script:
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php ./vendor/bin/coveralls -v; fi
