language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.3
          env: deps=low
        - php: 5.6
          env: deps=high
        - php: hhvm

env:
    global:
        - deps=no

install:
    - if [ "$symfony" = "no" ]; then composer --prefer-source --dev install; fi;
    - if [ "$symfony" = "low" ]; then composer --prefer-source --dev --prefer-lowest --prefer-stable update; fi;
    - if [ "$symfony" = "high" ]; then composer --prefer-source --dev update; fi;

script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
    - php ./vendor/bin/coveralls -v
